#!/bin/bash

echo "🚀 GPU RRD Monitor - Real Data Access"
echo "======================================"
echo ""
echo "✅ Real application is running with actual RRD data!"
echo ""
echo "📱 Access the dashboard at: http://localhost:5001"
echo ""
echo "🔍 This application now has access to:"
echo "   • Real RRD files from Observium"
echo "   • Temperature sensor data from 10.4.21.74"
echo "   • Site: DFW2 (10.4.*.* subnet)"
echo ""
echo "📊 Features available:"
echo "   • Site selection (DFW2)"
echo "   • Date range selection"
echo "   • Alert type filtering (Throttled, Thermally Failed, Both)"
echo "   • Real GPU temperature analysis"
echo ""
echo "🛑 To stop the real application:"
echo "   docker stop gpu-rrd-monitor-real"
echo ""
echo "📝 To view logs:"
echo "   docker logs -f gpu-rrd-monitor-real"
echo ""
echo "🧪 Test application (no real data) is still running on port 5000"
echo "   Access: http://localhost:5000"
