version: '3.8'

services:
  gpumon:
    build:
      context: .
      dockerfile: Dockerfile.prod.privileged
    container_name: gpumon-app-prod-privileged
    ports:
      - "8090:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - RRD_DATA_PATH=/app/data
    volumes:
      # Mount Observium RRD data directory with privileged access
      - /opt/docker/volumes/docker-observium_config/_data/rrd:/app/data:ro
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    privileged: true  # This gives the container elevated privileges
    security_opt:
      - seccomp:unconfined  # Disable seccomp for full access
    cap_add:
      - ALL  # Add all capabilities
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gpumon-network

networks:
  gpumon-network:
    driver: bridge
